<?php
require_once('model/Lieu.php');
require_once('model/Commercant.php');
require_once('model/CategorieCommerce.php');
require_once('model/Commerce.php');
require_once('model/CategorieProduit.php');
require_once('model/Produit.php');
require_once('model/BonPlan.php');
?>